# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alceu Ferraz Costa
email: alceufc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal web site by Alceu Ferraz Costa, PhD candidate in Computer Science.
  Working with data mining techniques to model user behavior and information
  cascades on social media.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alceufc.com" # the base hostname & protocol for your site
twitter_username: alceufc
github_username:  alceufc

# Build settings
markdown: kramdown
